IF(LRSpline_INCLUDE_DIRS AND LRSpline_LIBRARIES)
  SET(LRSpline_FIND_QUIETLY TRUE)
ENDIF(LRSpline_INCLUDE_DIRS AND LRSpline_LIBRARIES)

UNSET(LRSpline_INCLUDE_DIRS CACHE)
UNSET(LRSpline_LIBRARIES CACHE)

FIND_PATH(LRSpline_INCLUDE_DIRS
  NAMES LRSpline/LRSplineSurface.h
  PATHS "$ENV{HOME}/include"
  "$ENV{HOME}/install/include"
  /sima/libs/LRSpline/include
)

FIND_LIBRARY(LRSpline_LIBRARIES
  NAMES LRSpline
  PATHS "$ENV{HOME}/lib"
  "$ENV{HOME}/install/lib"
  /sima/libs/LRSpline/lib
  PATH_SUFFIXES LRSpline
)

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LRSpline DEFAULT_MSG
                                  LRSpline_INCLUDE_DIRS LRSpline_LIBRARIES)
IF(LRSpline_INCLUDE_DIRS)
  # Export version information
  EXECUTE_PROCESS(COMMAND cat "${LRSpline_INCLUDE_DIRS}/LRSpline/LRSpline_version.h" OUTPUT_VARIABLE LRSPLINE_HEADER)
  STRING(REGEX MATCH "LRSPLINE_VERSION_MAJOR ([0-9]+)" LRSPLINE_VERSION_MAJOR ${LRSPLINE_HEADER})
  STRING(REGEX REPLACE "LRSPLINE_VERSION_MAJOR ([0-9]+)" "\\1" LRSPLINE_VERSION_MAJOR "${LRSPLINE_VERSION_MAJOR}")
  STRING(REGEX MATCH "LRSPLINE_VERSION_MINOR ([0-9]+)" LRSPLINE_VERSION_MINOR ${LRSPLINE_HEADER})
  STRING(REGEX REPLACE "LRSPLINE_VERSION_MINOR ([0-9]+)" "\\1" LRSPLINE_VERSION_MINOR "${LRSPLINE_VERSION_MINOR}")
  STRING(REGEX MATCH "LRSPLINE_VERSION_PATCH ([0-9]+)" LRSPLINE_VERSION_PATCH ${LRSPLINE_HEADER})
  STRING(REGEX REPLACE "LRSPLINE_VERSION_PATCH ([0-9]+)" "\\1" LRSPLINE_VERSION_PATCH "${LRSPLINE_VERSION_PATCH}")
ENDIF(LRSpline_INCLUDE_DIRS)
